In [1]:
import pandas as pd

In [2]:
csv_path="../Sons_of_Analyst/glassdoor_jobs.csv"

In [3]:
jobs_df=pd.read_csv(csv_path)
jobs_df["Salary Estimate"].value_counts()

$105K-$138K (Glassdoor Est.)          130
$71K-$108K (Glassdoor Est.)            30
$105K-$117K (Glassdoor Est.)           30
$92K-$146K (Glassdoor Est.)            30
$112K-$149K (Glassdoor Est.)           30
$139K-$229K (Glassdoor Est.)           30
$88K-$133K (Glassdoor Est.)            30
$86K-$108K (Glassdoor Est.)            30
$90K-$109K (Glassdoor Est.)            30
$59K-$101K (Glassdoor Est.)            30
$106K-$143K (Glassdoor Est.)           30
$108K-$140K (Glassdoor Est.)           30
$83K-$99K (Glassdoor Est.)             30
$ 17-$ 23 Per Hour(Glassdoor Est.)     30
$49K-$88K (Glassdoor Est.)             30
$70K-$119K (Glassdoor Est.)            30
$41K-$73K (Glassdoor Est.)             30
$68K-$119K (Glassdoor Est.)            30
$72K-$121K (Glassdoor Est.)            30
$110K-$145K (Glassdoor Est.)           30
$60K-$124K (Glassdoor Est.)            30
$125K-$156K (Glassdoor Est.)           30
$48K-$91K (Glassdoor Est.)             30
$50K-$63K (Glassdoor Est.)             30
$57K-$94K (Glassdoor Est.)             30
$81K-$137K (Glassdoor Est.)            30
$73K-$128K (Glassdoor Est.)            30
$95K-$165K (Glassdoor Est.)            30
$81K-$102K (Glassdoor Est.)            30
$77K-$92K (Glassdoor Est.)             30
Name: Salary Estimate, dtype: int64

In [4]:
jobs_df.head(100)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist,$77K-$92K (Glassdoor Est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
1,Data Scientist,$77K-$92K (Glassdoor Est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,₹100 to ₹500 billion (INR),-1
2,Data Scientist,$77K-$92K (Glassdoor Est.),"By clicking the Apply button, I understand tha...",3.7,Takeda\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,₹500+ billion (INR),"Novartis, Baxter, Pfizer"
3,Data Scientist,$77K-$92K (Glassdoor Est.),Join Our Growing Team\nA career with A Place f...,3.0,A Place for Mom\n3.0,"Overland Park, KS","New York, NY",501 to 1000 employees,2000,Company - Private,Healthcare Services & Hospitals,Healthcare,Unknown / Non-Applicable,"Enlivant, Sunrise Senior Living, Brookdale Sen..."
4,Data Scientist,$77K-$92K (Glassdoor Est.),We are looking for Data Scientists who are int...,3.7,GovTech\n3.7,"San Francisco, CA","Singapore, Singapore",1001 to 5000 employees,2016,Government,Government Agencies,Government,Unknown / Non-Applicable,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Data Engineer,$90K-$109K (Glassdoor Est.),Hawkins Point Partners is looking to add a Dat...,4.6,HawkinsPointPartners\n4.6,"Cambridge, MA","Westford, MA",51 to 200 employees,2012,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,₹1 to ₹5 billion (INR),-1
96,Customer Data Scientist/Sales Engineer,$90K-$109K (Glassdoor Est.),Company Overview\n\nH2O.ai is the open source ...,4.1,h2o.ai\n4.1,"Chicago, IL","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
97,Data Scientist,$90K-$109K (Glassdoor Est.),Data Scientist\n\nAre you looking for a high e...,2.7,Relias\n2.7,"Morrisville, NC","Cary, NC",501 to 1000 employees,2012,Company - Private,Computer Hardware & Software,Information Technology,₹10 to ₹50 billion (INR),-1
98,Data Scientist,$90K-$109K (Glassdoor Est.),"As a Data Scientist, you'll utilize advanced q...",3.8,Via Transportation\n3.8,"New York, NY","New York, NY",501 to 1000 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,-1
99,Data Scientist – Causal & Predictive analytics...,$90K-$109K (Glassdoor Est.),Posting Title\nData Scientist – Causal & Predi...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,₹500+ billion (INR),-1

In [5]:
jobs_df["Salary Estimate"].unique()

array(['$77K-$92K (Glassdoor Est.)', '$108K-$140K (Glassdoor Est.)',
       '$ 17-$ 23 Per Hour(Glassdoor Est.)',
       '$90K-$109K (Glassdoor Est.)', '$106K-$143K (Glassdoor Est.)',
       '$41K-$73K (Glassdoor Est.)', '$139K-$229K (Glassdoor Est.)',
       '$105K-$117K (Glassdoor Est.)', '$57K-$94K (Glassdoor Est.)',
       '$95K-$165K (Glassdoor Est.)', '$50K-$63K (Glassdoor Est.)',
       '$48K-$91K (Glassdoor Est.)', '$110K-$145K (Glassdoor Est.)',
       '$70K-$119K (Glassdoor Est.)', '$72K-$121K (Glassdoor Est.)',
       '$49K-$88K (Glassdoor Est.)', '$125K-$156K (Glassdoor Est.)',
       '$68K-$119K (Glassdoor Est.)', '$73K-$128K (Glassdoor Est.)',
       '$86K-$108K (Glassdoor Est.)', '$92K-$146K (Glassdoor Est.)',
       '$83K-$99K (Glassdoor Est.)', '$88K-$133K (Glassdoor Est.)',
       '$112K-$149K (Glassdoor Est.)', '$71K-$108K (Glassdoor Est.)',
       '$60K-$124K (Glassdoor Est.)', '$81K-$102K (Glassdoor Est.)',
       '$81K-$137K (Glassdoor Est.)', '$59K-$101K (Glassdoor Est.)',
       '$105K-$138K (Glassdoor Est.)'], dtype=object)

In [6]:
average_salary=[]
for salary in jobs_df["Salary Estimate"]:
    
    if salary == ("$105K-$138K (Glassdoor Est.)"):
        average_salary.append(121500)
    elif average_salary == ("$68K-$119K (Glassdoor Est.)"):
        salary.append(93500)
    elif salary == ("$ 17-$ 23 Per Hour(Glassdoor Est.)"):
        average_salary.append(41600)
    elif salary == ("$50K-$63K (Glassdoor Est.)"):
        average_salary.append(56500)
    elif salary == ("$70K-$119K (Glassdoor Est.)"):
        average_salary.append(94500)
    elif salary == ("$106K-$143K (Glassdoor Est.)"):
        average_salary.append(124500)
    elif salary == ("$92K-$146K (Glassdoor Est.)"):
        average_salary.append(119000)
    elif salary == ("$112K-$149K (Glassdoor Est.)"):
        average_salary.append(130500)
    elif salary == ("$81K-$137K (Glassdoor Est.)"):
        average_salary.append(109000)
    elif salary == ("$57K-$94K (Glassdoor Est.)"):
        average_salary.append(75500) 
    elif salary == ("$86K-$108K (Glassdoor Est.)"):
        average_salary.append(97000)
    elif salary == ("$139K-$229K (Glassdoor Est.)"):
        average_salary.append(184000)
    elif salary == ("$60K-$124K (Glassdoor Est.)"):
        average_salary.append(92000)
    elif salary == ("$110K-$145K (Glassdoor Est.)"):
        average_salary.append(127500)
    elif salary == ("$90K-$109K (Glassdoor Est.)"):
        average_salary.append(99500)
    elif salary == ("$72K-$121K (Glassdoor Est.)"):
        average_salary.append(96500)
    elif salary == ("$88K-$133K (Glassdoor Est.)"):
        average_salary.append(110500)
    elif salary == ("$49K-$88K (Glassdoor Est.)"):
        average_salary.append(68500)
    elif salary == ("$59K-$101K (Glassdoor Est.)"):
        average_salary.append(80000)
    elif salary == ("$81K-$102K (Glassdoor Est.)"):
        average_salary.append(91500)
    elif salary == ("$77K-$92K (Glassdoor Est.)"):
        average_salary.append(16900)
    elif salary == ("$125K-$156K (Glassdoor Est.)"):
        average_salary.append(145500)
    elif salary == ("$105K-$117K (Glassdoor Est.)"):
        average_salary.append(111000)
    elif salary == ("$71K-$108K (Glassdoor Est.)"):
        average_salary.append(89500)
    elif salary == ("$41K-$73K (Glassdoor Est.)"):
        average_salary.append(57000)
    elif salary == ("$48K-$91K (Glassdoor Est.)"):
        average_salary.append(69500)
    elif salary == ("$108K-$140K (Glassdoor Est.)"):
        average_salary.append(126500)
    elif salary == ("$95K-$165K (Glassdoor Est.)"):
        average_salary.append(130000)
    elif salary == ("$73K-$128K (Glassdoor Est.)"):
        average_salary.append(100500)
    elif salary == ("$83K-$99K (Glassdoor Est.)"):
        average_salary.append(91000)
    else:
        average_salary.append(0)

print(average_salary)

[16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 16900, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 126500, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 41600, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 99500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 124500, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 57000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 184000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 111000, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 75500, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 130000, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 56500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 69500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 127500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 94500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 96500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 68500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 145500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 100500, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 97000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 119000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 91000, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 110500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 130500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 89500, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 92000, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 91500, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 109000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 80000, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500, 121500]

In [7]:
len(average_salary)

1000

In [8]:
jobs_df["salary_average"]=average_salary

In [9]:
jobs_df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,salary_average
0,Data Scientist,$77K-$92K (Glassdoor Est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",16900
1,Data Scientist,$77K-$92K (Glassdoor Est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,₹100 to ₹500 billion (INR),-1,16900
2,Data Scientist,$77K-$92K (Glassdoor Est.),"By clicking the Apply button, I understand tha...",3.7,Takeda\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,₹500+ billion (INR),"Novartis, Baxter, Pfizer",16900
3,Data Scientist,$77K-$92K (Glassdoor Est.),Join Our Growing Team\nA career with A Place f...,3.0,A Place for Mom\n3.0,"Overland Park, KS","New York, NY",501 to 1000 employees,2000,Company - Private,Healthcare Services & Hospitals,Healthcare,Unknown / Non-Applicable,"Enlivant, Sunrise Senior Living, Brookdale Sen...",16900
4,Data Scientist,$77K-$92K (Glassdoor Est.),We are looking for Data Scientists who are int...,3.7,GovTech\n3.7,"San Francisco, CA","Singapore, Singapore",1001 to 5000 employees,2016,Government,Government Agencies,Government,Unknown / Non-Applicable,-1,16900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Data Scientist,$105K-$138K (Glassdoor Est.),• Be one of the first to join our rapidly grow...,5.0,Shelf Engine\n5.0,"Seattle, WA","Seattle, WA",1 to 50 employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,121500
996,Analytic Consultant 4 - Branch Banking Reporti...,$105K-$138K (Glassdoor Est.),Job Description\n\nImportant Note: During the ...,3.6,Wells Fargo\n3.6,"Dallas, TX","San Francisco, CA",10000+ employees,1852,Company - Public,Banks & Building Societies,Finance,₹500+ billion (INR),-1,121500
997,Data Scientist,$105K-$138K (Glassdoor Est.),"THE COMPANY\n\nFannie Mae provides reliable, l...",3.6,Fannie Mae\n3.6,"Washington, DC","Washington, DC",5001 to 10000 employees,1938,Company - Public,Investment Banking & Asset Management,Finance,₹500+ billion (INR),Freddie Mac,121500
998,Data Scientist,$105K-$138K (Glassdoor Est.),Ready to write the best chapter of your career...,3.9,XSELL Technologies\n3.9,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,121500
999,Clinical Data Analyst,$105K-$138K (Glassdoor Est.),About Us:\n\nNYSTEC is a non-profit technology...,3.8,NYSTEC\n3.8,"New York, NY","Rome, NY",51 to 200 employees,1996,Non-profit Organisation,Consulting,Business Services,₹1 to ₹5 billion (INR),"KPMG, Accenture, Deloitte",121500